name: expense_tracker
description: Money tracker 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.3.18+82

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_riverpod: ^2.5.1
  sqflite: ^2.3.3
  path: ^1.9.0
  fl_chart: ^0.69.0
  collection: ^1.18.0
  salomon_bottom_bar: ^3.3.2
  flutter_svg: ^2.0.10+1
  flutter_slidable: ^3.1.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.3
  flutter_timezone: ^3.0.1
  in_app_review: ^2.0.9
  app_settings: ^5.1.1
  home_widget: ^0.7.0
  timezone: ^0.9.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: '#000C33'
  image: 'assets/icon/AppIcon.png'

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/flags/
    - assets/logo/
    - assets/icon/
    - lib/Configuration/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-L.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu-LI.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Ubuntu-R.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu-RI.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Ubuntu-M.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-MI.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Ubuntu-B.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-BI.ttf
          weight: 700
          style: italic
        
       